name: squire
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2
  mongo_dart: ^0.10.5
  json_annotation: ^4.9.0
  shelf_cors_headers: ^0.1.0
  cupertino_icons: ^1.0.8
  mockito: ^5.5.1
  http: ^1.5.0
  provider: ^6.1.5+1
  get_it: ^9.0.5

dev_dependencies:
  build_runner: ^2.6.0
  json_serializable: ^6.11.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/standees/

  fonts:
    - family: Tuff
      fonts:
        - asset: fonts/Tuff-Normal.ttf
        - asset: fonts/Tuff-Italic.ttf
          style: italic
        - asset: fonts/Tuff-Bold.ttf
          weight: 700
        - asset: fonts/Tuff-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Garamond
      fonts:
        - asset: fonts/Garamond-Bold.ttf
          weight: 700
